17:39:49.400 TRACE [19475] [FFSCENE_PYTHON] ffscene_python_t::open begin
17:39:49.413 TRACE [19475] [FFSCENE_PYTHON] ffscene_python_t::open end ok
17:40:19.529 ERROR [19475] [FFSCENE_PYTHON] ffscene_python_t::gen_verify_callback exception<'module' object has no attribute 'account_req_t'
Traceback (most recent call last):

  File "./pylib/ffext.py", line 108, in ff_session_verify
    ret = g_session_verify_callback(session_key, online_time, ip, gate_name)

  File "./pyproject/player/player_handler.py", line 22, in real_session_verify
    account = msg_def.account_req_t()

AttributeError: 'module' object has no attribute 'account_req_t'

>
