23:30:39.257 TRACE [5237] [FFSCENE_PYTHON] ffscene_python_t::open begin
23:30:39.268 TRACE [5237] [FFSCENE] ffscene_t::open begin
23:30:39.269 INFO  [5237] [FFRPC] ffrpc_t::connect_to_broker begin...host_<tcp://127.0.0.1:10241>,node_id_[0]
23:30:39.270 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
23:30:39.270 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[6] begin
23:30:39.270 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::open end ok m_node_id[6]
23:30:39.271 TRACE [5237] [FFSCENE] ffscene_t::open end ok
23:30:39.271 TRACE [5237] [FFSCENE_PYTHON] ffscene_python_t::open end ok
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[6],bind_broker_id[0]
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
23:30:39.271 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[0] begin
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[6],bind_broker_id[0]
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[12],bind_broker_id[0]
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
23:30:39.392 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
23:30:41.697 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:30:41.697 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[3] begin
23:30:41.697 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:30:41.700 TRACE [5237] [FFSCENE] ffscene_t::send_msg_session begin session_id_<4360573304>
23:30:41.700 TRACE [5237] [FFSCENE] ffscene_t::send_msg_session end ok gate[gate@0]
23:30:41.700 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter end ok
23:30:41.700 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:30:41.700 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:30:41.700 TRACE [5237] [FFRPC] ffrpc_t::call_impl begin service_name_<gate@0>, msg_name_<ff::gate_route_msg_to_session_t::in_t>
23:30:41.700 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:30:41.700 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<5>, callback_id_[0] end ok
23:30:41.700 TRACE [5237] [FFRPC] ffrpc_t::call_impl msgid<5> callback_id[0] end ok
23:30:41.700 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:30:41.701 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[3] end ok
23:30:41.743 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:30:41.743 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[1] begin
23:30:41.743 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call begin cmd[8011]
23:30:41.743 INFO  [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[10]
23:30:41.745 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 271, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
23:30:41.745 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call end ok
23:30:41.745 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:30:41.745 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:30:41.745 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:30:41.747 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[12], broker_node_id[0], msgid<0>, callback_id_[1] end ok
23:30:48.550 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:30:48.550 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[6] begin
23:30:48.550 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:30:48.551 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 25, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 94, in load_player
    callback(dictRet)

  File "./pyproject/room_service/main.py", line 17, in OnLoadPlayerDataDone
    room_mgr.OnPlayerEnterScene(roomPlayer)

  File "./pyproject/room_service/room_mgr.py", line 14, in OnPlayerEnterScene
    entity_mgr.AddEntity(roomPlayer.GetSession(), roomPlayer)

  File "./pyproject/entity/entity_mgr.py", line 7, in AddEntity
    assert session not in g_dictAllEntity

AssertionError

>
23:30:48.551 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter end ok
23:30:48.551 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:30:48.551 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:30:48.551 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:30:48.552 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[6] end ok
23:30:55.405 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:30:55.405 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[2] begin
23:30:55.405 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call begin cmd[8011]
23:30:55.405 INFO  [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[10]
23:30:55.405 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 271, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
23:30:55.405 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call end ok
23:30:55.405 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:30:55.405 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:30:55.405 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:30:55.405 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[12], broker_node_id[0], msgid<0>, callback_id_[2] end ok
23:30:56.331 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:30:56.331 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[9] begin
23:30:56.331 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:30:56.332 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 25, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 94, in load_player
    callback(dictRet)

  File "./pyproject/room_service/main.py", line 17, in OnLoadPlayerDataDone
    room_mgr.OnPlayerEnterScene(roomPlayer)

  File "./pyproject/room_service/room_mgr.py", line 14, in OnPlayerEnterScene
    entity_mgr.AddEntity(roomPlayer.GetSession(), roomPlayer)

  File "./pyproject/entity/entity_mgr.py", line 7, in AddEntity
    assert session not in g_dictAllEntity

AssertionError

>
23:30:56.332 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter end ok
23:30:56.332 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:30:56.332 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:30:56.332 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:30:56.332 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[9] end ok
23:30:57.172 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:30:57.172 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[3] begin
23:30:57.172 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call begin cmd[8011]
23:30:57.172 INFO  [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[10]
23:30:57.173 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 271, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
23:30:57.173 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call end ok
23:30:57.173 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:30:57.173 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:30:57.173 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:30:57.173 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[12], broker_node_id[0], msgid<0>, callback_id_[3] end ok
23:31:03.971 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:31:03.971 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[12] begin
23:31:03.971 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:31:03.972 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 25, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 94, in load_player
    callback(dictRet)

  File "./pyproject/room_service/main.py", line 17, in OnLoadPlayerDataDone
    room_mgr.OnPlayerEnterScene(roomPlayer)

  File "./pyproject/room_service/room_mgr.py", line 14, in OnPlayerEnterScene
    entity_mgr.AddEntity(roomPlayer.GetSession(), roomPlayer)

  File "./pyproject/entity/entity_mgr.py", line 7, in AddEntity
    assert session not in g_dictAllEntity

AssertionError

>
23:31:03.972 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter end ok
23:31:03.972 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:31:03.972 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:31:03.972 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:31:03.972 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[12] end ok
23:31:04.737 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:31:04.737 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[4] begin
23:31:04.737 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call begin cmd[8011]
23:31:04.737 INFO  [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[10]
23:31:04.737 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 271, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
23:31:04.737 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call end ok
23:31:04.737 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:31:04.737 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:31:04.737 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:31:04.737 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[12], broker_node_id[0], msgid<0>, callback_id_[4] end ok
23:31:05.738 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:31:05.738 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[15] begin
23:31:05.738 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:31:05.739 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 25, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 94, in load_player
    callback(dictRet)

  File "./pyproject/room_service/main.py", line 17, in OnLoadPlayerDataDone
    room_mgr.OnPlayerEnterScene(roomPlayer)

  File "./pyproject/room_service/room_mgr.py", line 14, in OnPlayerEnterScene
    entity_mgr.AddEntity(roomPlayer.GetSession(), roomPlayer)

  File "./pyproject/entity/entity_mgr.py", line 7, in AddEntity
    assert session not in g_dictAllEntity

AssertionError

>
23:31:05.739 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter end ok
23:31:05.739 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:31:05.739 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:31:05.739 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:31:05.739 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[15] end ok
23:31:06.284 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:31:06.284 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[5] begin
23:31:06.284 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call begin cmd[8011]
23:31:06.284 INFO  [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[10]
23:31:06.285 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 271, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
23:31:06.285 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call end ok
23:31:06.285 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:31:06.285 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:31:06.285 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:31:06.285 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[12], broker_node_id[0], msgid<0>, callback_id_[5] end ok
23:31:11.326 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:31:11.326 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[9],callback_id[18] begin
23:31:11.326 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter begin gate[gate@0]
23:31:11.327 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_enter_callback exception<
Traceback (most recent call last):

  File "./pylib/ffext.py", line 104, in ff_session_enter
    return g_session_enter_callback(session_id, from_scene, extra_data)

  File "./pyproject/room_service/main.py", line 25, in OnPlayerEnterScene
    dbservice.load_player(session, OnLoadPlayerDataDone)

  File "./pyproject/db/dbservice.py", line 94, in load_player
    callback(dictRet)

  File "./pyproject/room_service/main.py", line 17, in OnLoadPlayerDataDone
    room_mgr.OnPlayerEnterScene(roomPlayer)

  File "./pyproject/room_service/room_mgr.py", line 14, in OnPlayerEnterScene
    entity_mgr.AddEntity(roomPlayer.GetSession(), roomPlayer)

  File "./pyproject/entity/entity_mgr.py", line 7, in AddEntity
    assert session not in g_dictAllEntity

AssertionError

>
23:31:11.327 TRACE [5237] [FFSCENE] ffscene_t::process_session_enter end ok
23:31:11.327 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:31:11.327 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:31:11.327 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:31:11.327 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[1], broker_node_id[0], msgid<0>, callback_id_[18] end ok
23:31:15.252 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
23:31:15.252 TRACE [5237] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[6] begin
23:31:15.252 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call begin cmd[8011]
23:31:15.253 INFO  [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[10]
23:31:15.253 ERROR [5237] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 271, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
23:31:15.253 TRACE [5237] [FFSCENE] ffscene_t::process_scene_call end ok
23:31:15.253 INFO  [5237] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
23:31:15.253 TRACE [5237] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
23:31:15.253 INFO  [5237] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
23:31:15.253 TRACE [5237] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[12], broker_node_id[0], msgid<0>, callback_id_[6] end ok
