20:09:38.317 TRACE [26671] [FFSCENE_PYTHON] ffscene_python_t::open begin
20:09:38.557 TRACE [26671] [FFSCENE] ffscene_t::open begin
20:09:38.559 INFO  [26671] [FFRPC] ffrpc_t::connect_to_broker begin...host_<tcp://127.0.0.1:10241>,node_id_[0]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] begin
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data node_id[12] begin
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::route_logic_msg_t::in_t] -> msg id[7]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::scene_call_msg_t::in_t] -> msg id[8]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_enter_scene_t::in_t] -> msg id[9]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_offline_t::in_t] -> msg id[10]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data msg name[ff::session_verify_t::in_t] -> msg id[11]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data name[gate@0] -> node id[1],bind_broker_id[0]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@0] -> node id[6],bind_broker_id[0]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data name[scene@1] -> node id[12],bind_broker_id[0]
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_sync_data end ok
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[5] call end ok
20:09:38.559 TRACE [26671] [FFRPC] ffrpc_t::open end ok m_node_id[12]
20:09:38.559 TRACE [26671] [FFSCENE] ffscene_t::open end ok
20:09:38.559 TRACE [26671] [FFSCENE_PYTHON] ffscene_python_t::open end ok
20:10:02.947 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
20:10:02.947 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[2] begin
20:10:02.947 TRACE [26671] [FFSCENE] ffscene_t::process_scene_call begin cmd[200]
20:10:02.947 INFO  [26671] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[15]
20:10:02.948 ERROR [26671] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 269, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
20:10:02.948 TRACE [26671] [FFSCENE] ffscene_t::process_scene_call end ok
20:10:02.948 INFO  [26671] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
20:10:02.948 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
20:10:02.948 INFO  [26671] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
20:10:02.948 TRACE [26671] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[6], broker_node_id[0], msgid<0>, callback_id_[2] end ok
20:10:14.004 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
20:10:14.004 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[4] begin
20:10:14.004 TRACE [26671] [FFSCENE] ffscene_t::process_scene_call begin cmd[200]
20:10:14.004 INFO  [26671] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[15]
20:10:14.004 ERROR [26671] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 269, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
20:10:14.004 TRACE [26671] [FFSCENE] ffscene_t::process_scene_call end ok
20:10:14.005 INFO  [26671] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
20:10:14.005 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
20:10:14.005 INFO  [26671] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
20:10:14.005 TRACE [26671] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[6], broker_node_id[0], msgid<0>, callback_id_[4] end ok
20:10:26.617 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
20:10:26.617 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[6] begin
20:10:26.617 TRACE [26671] [FFSCENE] ffscene_t::process_scene_call begin cmd[200]
20:10:26.617 INFO  [26671] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[15]
20:10:26.617 ERROR [26671] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 269, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
20:10:26.617 TRACE [26671] [FFSCENE] ffscene_t::process_scene_call end ok
20:10:26.617 INFO  [26671] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
20:10:26.617 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
20:10:26.617 INFO  [26671] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
20:10:26.617 TRACE [26671] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[6], broker_node_id[0], msgid<0>, callback_id_[6] end ok
20:10:51.889 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] begin
20:10:51.889 TRACE [26671] [FFRPC] ffrpc_t::handle_broker_route_msg msg_id[8],callback_id[8] begin
20:10:51.889 TRACE [26671] [FFSCENE] ffscene_t::process_scene_call begin cmd[200]
20:10:51.889 INFO  [26671] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback len[15]
20:10:51.889 ERROR [26671] [FFSCENE_PYTHON] ffscene_python_t::gen_scene_call_callback exception<'NoneType' object is not callable
Traceback (most recent call last):

  File "./pylib/ffext.py", line 269, in ff_scene_call
    ret = func(msg_)

TypeError: 'NoneType' object is not callable

>
20:10:51.889 TRACE [26671] [FFSCENE] ffscene_t::process_scene_call end ok
20:10:51.889 INFO  [26671] [FFRPC] ffrpc_t::handle_broker_route_msg end ok msg_.bridge_route_id=0
20:10:51.889 TRACE [26671] [FFRPC] ffrpc_t::handle_msg_impl cmd[6] call end ok
20:10:51.889 INFO  [26671] [FFRPC] ffbroker_t::send_to_broker_by_nodeid begin bridge_route_id_[0]
20:10:51.889 TRACE [26671] [FFRPC] ffrpc_t::send_to_broker_by_nodeid dest_node_id[6], broker_node_id[0], msgid<0>, callback_id_[8] end ok
